name: Verify Project

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    defaults:
      run:
        shell: bash
        working-directory: ./my_move_module

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config libclang-dev

      - name: Install Sui CLI (pinned)
        run: |
          set -euo pipefail
          VER=1.31.0   # set to the Sui version your package targets
          curl -L "https://github.com/MystenLabs/sui/releases/download/v${VER}/sui-${VER}-ubuntu-x86_64.tgz" -o sui.tgz
          sudo tar -xzf sui.tgz -C /usr/local/bin sui
          sui --version

      - name: Build Move project
        run: sui move build

      - name: Run Move tests
        env:
          RUST_LOG: info
        run: sui move test -v