name: Verify Project

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Sui tools image
        run: docker pull mysten/sui-tools:mainnet-v1.54.2

      - name: Build Move project
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace/my_move_module \
            mysten/sui-tools:mainnet-v1.54.2 \
            sui move build

      - name: Run Move tests
        env:
          RUST_LOG: info
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace/my_move_module \
            mysten/sui-tools:mainnet-v1.54.2 \
            sui move test -v